out = list()
out.append([x for x in range(0,53,4)])
out.append([x for x in range(20,8,-1)])
out.append([x**2 for x in range(1,13)])
out.append([(-1)**(x+1)*(2*x+1) for x in range(13)])
out.append([x for x in [1,2,3,4,0,1,2,3,4,0,1,2,3]])
out.append([x for x in ['a','c','e','g','i','k','m']])
out.append(['*'*n for n in range(1,10,2)])
out.append([' '*(9-n)+'*'*(n) for n in range(1,10,2)])
out.append([[0,0,0,0] for i in range(4)])
out.append([[i,i,i,i] for i in range(4)])
out.append([[0,1,2,3,4][0:i] for i in range(1,6)])
out.append([{i:i**3} for i in range(1,6)])
for o in out:
    print(o)
